name: Build and deploy ENSNode

on:
  push:
    branches:
      - feat/railway-ensnode-deployments
      - main
      - alpha
      - subgraph

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.deterimne_tag.outputs.tag }}
      output2: ${{ steps.deterimne_tag.outputs.svc_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Branch Name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    
      # We need to recognize which branch had push incomin
      # Based on that create Docker image with corresponding label - use TAG variable for this
      # For alhpa/subgraph TAG we need also to specify corresponding Railway SVC_ID which is used for service redeployment
      - name: Determine tag
        id: deterimne_tag
        run: |
            case "$BRANCH" in
              "main")
                echo "TAG=latest" >> $GITHUB_ENV
                ;;
              "alpha")
                echo "TAG=alpha" >> $GITHUB_ENV
                echo "SVC_ID=${{ secrets.ALPHA_SVC_ID }}" >> "$GITHUB_OUTPUT"
                ;;
              "subgraph")
                echo "TAG=subgraph" >> $GITHUB_ENV
                echo "SVC_ID=${{ secrets.SUBGRAPH_SVC_ID }}" >> "$GITHUB_OUTPUT"
                ;;
              "feat/railway-ensnode-deployments")
                echo "TAG=latest" >> $GITHUB_ENV
                ;;
              *)
                echo "Branch not recognized, skipping workflow"
                exit 1
            esac
            echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
            
      - name: Build & Push Docker image for the ENSNode
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository }}/ensnode
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -f apps/ensnode/Dockerfile -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    needs: image-build-and-push
    if:  ${{ needs.image-build-and-push.outputs.svc_id }}
    env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SVC_ID: ${{ needs.image-build-and-push.outputs.svc_id }}
    steps:
      - name: Deploy ENSNode on Railway
        run: |
         railway redeploy --service ${{ env.SVC_ID }} --yes
            